---
- name: Check for Xorg Configuration Directory
  ansible.builtin.stat:
    path: /etc/X11/xorg.conf.d
  register: screen_power_xorg_dir

- name: Disable X11 DPMS to Prevent Random Screen Blackening
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/00-disable-dpms.conf
    content: |
      Section "Monitor"
          Identifier "Monitor0"
          Option "DPMS" "false"
      EndSection

      Section "ServerLayout"
          Identifier "ServerLayout0"
          Option "StandbyTime" "0"
          Option "SuspendTime" "0"
          Option "OffTime" "0"
          Option "BlankTime" "0"
      EndSection
    mode: '0644'
  when: screen_power_xorg_dir.stat.exists
