---
- name: Check for GRUB Configuration File
  ansible.builtin.stat:
    path: /etc/default/grub
  register: kernel_tuning_grub_config

- name: Enable PSI on Kernel Command Line
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!\bpsi=1\b).)*)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 psi=1"'
    backrefs: true
  register: kernel_tuning_grub_updated
  when: kernel_tuning_grub_config.stat.exists

- name: Update Bootloader to Persist Kernel Parameters (Debian)
  ansible.builtin.command: update-grub
  when:
    - kernel_tuning_grub_config.stat.exists
    - kernel_tuning_grub_updated.changed
    - ansible_facts['os_family'] == 'Debian'
  changed_when: true

- name: Update Bootloader to Persist Kernel Parameters (RedHat)
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when:
    - kernel_tuning_grub_config.stat.exists
    - kernel_tuning_grub_updated.changed
    - ansible_facts['os_family'] == 'RedHat'
  changed_when: true
