---
- name: Apply High Responsiveness Virtual Memory Engine Parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-oom-tuning.conf
    state: present
    reload: true
  loop:
    - {key: 'vm.swappiness', value: '100'}
    - {key: 'vm.watermark_scale_factor', value: '{{ system_discovery_watermark_scale_factor }}'}
    - {key: 'vm.vfs_cache_pressure', value: '50'}
