---
- name: Write Node.js Heap Limit to /etc/profile.d
  ansible.builtin.copy:
    dest: /etc/profile.d/node_heap_limit.sh
    content: |
      export NODE_OPTIONS="--max-old-space-size={{ dev_throttling_node_heap_mb }}"
    mode: '0644'
