---
- name: Locate systemd-oomd Unit Files on Disk
  ansible.builtin.find:
    paths:
      - /etc/systemd/system
      - /usr/lib/systemd/system
      - /run/systemd/system
      - /lib/systemd/system
    patterns: "systemd-oomd*"
  register: oom_handler_oomd_unit_find

- name: Mask Systemd-Oomd to Prevent Kernel Swapping OOM Interference
  ansible.builtin.file:
    src: /dev/null
    dest: "/etc/systemd/system/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ oom_handler_oomd_unit_find.files }}"
  when: oom_handler_oomd_unit_find.files | length > 0
