---
- name: Write ZRAM Generator Configuration
  ansible.builtin.copy:
    dest: /etc/systemd/zram-generator.conf
    content: |
      [zram0]
      zram-size = {{ system_discovery_target_zram_mb }}M
      compression-algorithm = zstd
      options = pri=100
    mode: '0644'
  register: zram_swap_config_redhat
  when: ansible_facts['os_family'] in ['RedHat', 'Archlinux']

- name: Check ZRAM Generator Service Registration
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/systemd-zram-setup@.service
  register: zram_swap_generator_check
  when: ansible_facts['os_family'] in ['RedHat', 'Archlinux']

- name: Restart and Enable ZRAM Generator Service (RedHat/Arch)
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0
    state: restarted
    enabled: true
    daemon_reload: true
  when:
    - ansible_facts['os_family'] in ['RedHat', 'Archlinux']
    - zram_swap_config_redhat.changed
    - zram_swap_generator_check.stat.exists
