---
- name: Install ZRAM Package for Target OS Family
  ansible.builtin.package:
    name: >-
      {{ (ansible_facts['os_family'] == 'Debian')
      | ternary('zram-tools', 'zram-generator') }}
    state: present
