---
- name: Install ZRAM Package for Target OS Family
  ansible.builtin.package:
    name: >-
      {{ (ansible_facts['os_family'] == 'Debian')
      | ternary('zram-tools',
        (ansible_facts['os_family'] == 'RedHat')
        | ternary('systemd-zram-generator', 'zram-generator')) }}
    state: present
