---
- name: List Active Swap Devices
  ansible.builtin.command: swapon --show=NAME --noheadings
  register: zram_swap_active_swaps
  changed_when: false

- name: Disable All Non-ZRAM Swap Devices
  ansible.builtin.command: "swapoff {{ item }}"
  loop: "{{ zram_swap_active_swaps.stdout_lines }}"
  when: zram_swap_active_swaps.stdout_lines | length > 0 and 'zram' not in item
  changed_when: true

- name: Comment Out Disk Swap Entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#]\S+\s+\S+\s+swap\s+.*)$'
    replace: '# Removed by Performance Automation Tuning Framework: \1'
